export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_INPUT = 'CLEAR_INPUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_CHANNELS = 'GET_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';

export const CHANNELS_LOADING = 'CHANNELS_LOADING';
